In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mobile-price-classification/train.csv
/kaggle/input/mobile-price-classification/test.csv


<h1> Mobile Price Classification </h1>

In [2]:
import warnings
warnings.simplefilter("ignore")

In [3]:
df = pd.read_csv("../input/mobile-price-classification/train.csv")

In [4]:
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [5]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [7]:
df.describe()

battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    645.108000  1251.515500  2124.213000    12.306500     5.767000   
std     443.780811   432.199447  1084.732044     4.213245     4.356398   
min       0.000000   500.000000   256.000000     5.000000     0.000000   
25%     282.750000   874.750000  1207.500000     9.000000     2.000000   
50%     564.000000  1247.000000  2146.500000    12.000000     5.000000   
75%     947.250000  1633.000000  3064.500000    16.000000     9.000000   
max    1960.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean     11.011000     0.761500      0.503000     0.507000     1.500000  
std       5.463955     0.426273      0.500116     0.500076     1.118314  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       6.000000     1.000000      0.000000     0.000000     0.750000  
50%      11.000000     1.000000      1.000000     1.000000     1.500000  
75%      16.000000     1.000000      1.000000     1.000000     2.250000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [8]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [9]:
Xall = df.drop('price_range',axis=1)
yall = df['price_range']

<h1> Hold-Out Validation </h1>

In [10]:
from sklearn.model_selection import train_test_split
X, Xtmp, y, ytmp = train_test_split(Xall, yall, test_size=0.4, random_state=0)
Xv, Xt, yv, yt = train_test_split(Xtmp, ytmp, test_size=0.5, random_state=0)

In [11]:
from sklearn.preprocessing import MinMaxScaler
scl = MinMaxScaler().fit(X)
X = scl.transform(X)
Xv = scl.transform(Xv)
Xt = scl.transform(Xt)

In [12]:
import torch
class MLP(torch.nn.Module):  
 def __init__(self, n_inputs, num_classes, dropout):  
    super(MLP, self).__init__()  
    self.hidden1 = torch.nn.Linear(n_inputs, 30) 
    self.act1 = torch.nn.ReLU() 
    self.hidden2 = torch.nn.Linear(30, 20) 
    self.act2 = torch.nn.ReLU() 
    self.output = torch.nn.Linear(20, num_classes) 
    self.dropout = torch.nn.Dropout(p=dropout) 
 
 def forward(self, X): 
    X = self.hidden1(X)
    X = self.act1(X)
    X = self.hidden2(X)
    X = self.act2(X)
    X = self.dropout(X)
    X = self.output(X)
    return X

In [13]:
X

array([[0.76887108, 0.        , 0.04      , ..., 1.        , 0.        ,
        0.        ],
       [0.19505678, 1.        , 0.92      , ..., 1.        , 1.        ,
        0.        ],
       [0.84502338, 1.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.46025384, 0.        , 0.6       , ..., 0.        , 0.        ,
        1.        ],
       [0.46092184, 0.        , 0.76      , ..., 1.        , 1.        ,
        1.        ],
       [0.13694055, 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ]])

In [14]:
y

891     3
1796    1
1868    3
1042    2
996     2
       ..
835     3
1216    1
1653    3
559     0
684     1
Name: price_range, Length: 1200, dtype: int64

In [15]:
from torch.utils.data import DataLoader, TensorDataset #เหมือนตัวเก็บข้อมูล ข้อมูลต้องเป็น float32 เท่านั้น และทำนายต้องเป็น int64 เท่านั้น
X = torch.from_numpy(X.astype(np.float32))   #ค่า x เป็น numpy อยู่แล้ว
y = torch.from_numpy(y.values.astype(np.int64)) #เปลี่ยนให้เป็น numpy array และเป็น int64

Xv = torch.from_numpy(Xv.astype(np.float32))
yv = torch.from_numpy(yv.values.astype(np.int64))

Xt = torch.from_numpy(Xt.astype(np.float32))
yt = torch.from_numpy(yt.values.astype(np.int64)) #บอกว่า true ก็เทรนสุ่ม 32 ตัวและเทรนไปเรื่อยๆ false โหลดทั้งหมดเข้าไปให้ทำนายเลย

train_dl = DataLoader(TensorDataset(X, y), batch_size=32, shuffle=True) #dataloader โหลดข้อมูลของเราเข้าไปใน deep learning เข้าไปเทรนทีละ 32 ตัวจนครบข้อมูลทั้งหมด
val_dl = DataLoader(TensorDataset(Xv, yv), batch_size=32, shuffle=False)
test_dl = DataLoader(TensorDataset(Xt, yt), batch_size=32, shuffle=False)

In [16]:
np.unique(y)

array([0, 1, 2, 3])

In [17]:
n_train, n_feat = X.shape
model = MLP(n_feat, 4, 0.5)                                   # 0.5 คือค่า dropout กัน overfiting
loss = torch.nn.CrossEntropyLoss()                            # ประกาศไว้ว่าจะหาความต่างระหว่าง output กับค่าโมเดล
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)  # จัดการเรื่องปรับจูนโมเดลต่างๆ optim.Adam เก่งที่สุดในการปรับค่าโมเดล lr(learning) คือความเร็วในการเรียนรู้ ปรับได้ตามใจ 0.1 - 0.000000001 เปลี่ยนแล้วดุว่า validation แม่นขึ้นไหม
for epoch in range(200):                                      # 20 รอบ พอไหมขึ้นอยู่กับ lr เรียน 100 รอบอาจจะเอ๋อนะคับ หมายถึงผมอะ
    model.train()                                             # Model in training mode เตรียมเรียนรู้
    tr_loss = []                                              # อยากเอาไว้เก็บค่า loss ที่เกิดขึ้นในแต่ละรอบ
    for i, (inputs, targets) in enumerate(train_dl): 
        optimizer.zero_grad()                                 # Clear gradients ค่าที่ต้องจูน ปรับให้เป็น 0 ก่อน 
        output = model(inputs)                                # Use forward pass เอา input เข้าไป เพื่อหา output
        l= loss(output, targets)                              # Calculate loss
        l.backward()                                          # Calculate gradients คำนวณว่าจะปรับอะไรเท่าไหร่ดี
        optimizer.step()                                      # Update model ปรับให้ค่าดีขึ้น
        tr_loss.append(l.item())                              # วนไปเรียนรู้เรื่อยๆ

        
#Validation

    model.eval() # Model in evaluation mode
    val_loss = []
    val_acc = []
    for i, (inputs, targets) in enumerate(val_dl):
        with torch.no_grad():
            output = model(inputs) 
        l= loss(output, targets)
        yp = torch.argmax(output, dim=1).flatten() ##
        val_acc.append(sum(yp==targets) / len(yp))
        val_loss.append(l.item())
 
    print("Train loss "+str(np.mean(tr_loss))+",Val loss "+str(np.mean(val_loss)) + ", Val Acc" + str(np.mean(val_acc))) #มาหาค่าเฉลี่ย

Train loss 1.3905864483431767,Val loss 1.3766303887734046, Val Acc0.3028846
Train loss 1.3772640416496678,Val loss 1.3687632450690637, Val Acc0.31971154
Train loss 1.3726655119343807,Val loss 1.3525804097835834, Val Acc0.38942307
Train loss 1.3417078852653503,Val loss 1.3121878000406118, Val Acc0.43028846
Train loss 1.2933613657951355,Val loss 1.2392708980120146, Val Acc0.6081731
Train loss 1.2056731550317061,Val loss 1.116332274216872, Val Acc0.6370192
Train loss 1.0951612356461977,Val loss 0.9880989927511948, Val Acc0.68509614
Train loss 0.9937082654551456,Val loss 0.8880357192112849, Val Acc0.68509614
Train loss 0.9109644513381155,Val loss 0.8171243438353906, Val Acc0.68990386
Train loss 0.8440022405825163,Val loss 0.7517840357927176, Val Acc0.7379808
Train loss 0.7879112472659663,Val loss 0.6845797850535467, Val Acc0.80528843
Train loss 0.750150054693222,Val loss 0.6404573413041922, Val Acc0.81971157
Train loss 0.7147175779468135,Val loss 0.6086486577987671, Val Acc0.81971157
Train

In [18]:
output

tensor([[  -8.7076,    6.0595,   -4.8808,  -44.1942],
        [  22.4561,   13.1294,  -28.3669, -113.7383],
        [  15.7327,   10.5210,  -19.1701,  -85.7944],
        [-103.8163,    2.8705,   11.6997,   15.4350],
        [ -55.8289,    2.8543,    7.0775,   -7.3977],
        [ -46.8361,    3.0779,    6.3208,  -13.8710],
        [ -49.1176,    2.9440,    6.4836,  -11.2981],
        [-101.6085,    2.8036,   11.4576,   15.1199],
        [  -8.3015,    6.4861,   -5.0891,  -48.2773],
        [  18.0321,   11.3052,  -21.6968,  -96.1022],
        [  21.1376,   12.0585,  -26.7406, -106.0964],
        [ -54.6555,    2.3119,    6.7064,   -2.3840],
        [  12.6952,    9.1878,  -14.6947,  -73.4482],
        [ -62.3673,    2.2442,    7.4224,    2.1613],
        [ -98.5441,    2.7003,   11.1128,   14.6776],
        [ -46.9764,    2.9608,    6.2784,  -12.6035]])

In [19]:
output.argmax(dim=1)

tensor([1, 0, 0, 3, 2, 2, 2, 3, 1, 0, 0, 2, 0, 2, 3, 2])

In [20]:
model.eval() # Model in evaluation mode
ts_loss = []
yp = []
for i, (inputs, targets) in enumerate(val_dl):
    with torch.no_grad():
            output = model(inputs) 
    pred = torch.argmax(output, dim=1).flatten() 
    yp = list(pred.cpu().numpy()) if len(yp) == 0 else yp + list(pred.cpu().numpy()) 
sum(yp==yv.cpu().numpy())/len(yv)

0.96

In [21]:
model.eval() # Model in evaluation mode
ts_loss = []
yp = []
for i, (inputs, targets) in enumerate(test_dl):
    with torch.no_grad():
         output = model(inputs)
    pred = torch.argmax(output, dim=1).flatten()
    yp = list(pred.cpu().numpy()) if len(yp) == 0 else yp + list(pred.cpu().numpy()) 
sum(yp==yt.cpu().numpy())/len(yt)

0.9425