In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

<h1> NumPy Array </h1>

In [2]:
import numpy as np

In [3]:
L = [1,2,3,4,5,6,7,8,9,10]
a = np.array(L)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a.shape

(10,)

In [5]:
b = a.reshape(10,1) 
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [6]:
b.shape

(10, 1)

In [7]:
a[0]

1

In [8]:
a[2:5]

array([3, 4, 5])

In [9]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [10]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [11]:
a[-2]

9

In [12]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [13]:
a[-5:-1]

array([6, 7, 8, 9])

In [14]:
np.size(a)

10

In [15]:
np.shape(a)

(10,)

In [16]:
[[1,2,3],
 [4,5,6],
 [7,8,9]]
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.shape(a)

(3, 3)

In [18]:
a[0,0]

1

In [19]:
a[1,:]

array([4, 5, 6])

In [20]:
a[:,-1]

array([3, 6, 9])

In [21]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [22]:
np.size(a,1)

3

In [23]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
np.size(b,1)

3

In [24]:
np.size(b,1)

3

In [25]:
np.ndim(b)

2

หรือ

In [26]:
a.ndim

2

<h1> Data is Matrix </h1>

rows = samples
columns = attributes, features

In [27]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U21')

In [28]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

<h2> Type of Matrix </h2>

In [29]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [30]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [31]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [32]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [33]:
c*d

array([[8., 0.],
       [0., 8.]])

In [34]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [35]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [36]:
np.empty([5,5])

array([[4.64959244e-310, 0.00000000e+000, 2.12199579e-314,
        1.42682308e+188, 5.87530072e+228],
       [1.31043528e-306, 5.50963561e-310, 1.42682308e+188,
        7.35163882e+228, 4.23000438e+180],
       [9.54109380e+179, 1.42547396e+188, 1.16715159e+180,
        5.95125947e+228, 1.42682255e+188],
       [1.57789222e+214, 2.15679996e-080, 3.03183028e+180,
        3.62048253e+262, 3.75212096e+199],
       [8.96365676e+276, 2.88067937e+214, 4.32910370e-304,
        3.62481865e+228, 2.51968621e+180]])

<h2> Random </h2>

In [37]:
import numpy as np
rng = np.random.RandomState(0)  # 0 is SEED
rng.rand()

0.5488135039273248

In [38]:
rng.randint(1, 5)

2

In [39]:
rng.rand(5,5)

array([[0.84426575, 0.85794562, 0.84725174, 0.6235637 , 0.38438171],
       [0.29753461, 0.05671298, 0.27265629, 0.47766512, 0.81216873],
       [0.47997717, 0.3927848 , 0.83607876, 0.33739616, 0.64817187],
       [0.36824154, 0.95715516, 0.14035078, 0.87008726, 0.47360805],
       [0.80091075, 0.52047748, 0.67887953, 0.72063265, 0.58201979]])

In [40]:
np.round(np.random.rand(5,5)*1000)

array([[802., 697., 771.,  54., 459.],
       [ 30., 636., 334., 785., 887.],
       [950., 345., 446., 172., 388.],
       [759., 358., 780., 780., 849.],
       [578., 803., 713.,  62., 918.]])

In [41]:
rng.randint(0,2, (5,5))

array([[1, 1, 0, 1, 0],
       [0, 1, 1, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 1, 0]])

In [42]:
a = [1,2,3,4,5,6,7,8,9,10]
rng.choice(a,5) 

array([10,  9,  2,  2,  8])

In [43]:
a = [1,2,3,4,5,6,7,8,9,10]
rng.choice(a,5, replace = False)

array([5, 2, 6, 1, 8])

In [44]:
rng.choice(10,3)

array([5, 9, 4])

In [45]:
np_matrix = rng.rand(1000,5)
idx_choose = rng.choice(1000,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.3823418 , 0.9347812 , 0.46958814, 0.21595956, 0.51462488],
       [0.767608  , 0.48523915, 0.11693227, 0.87617916, 0.80452459],
       [0.0887773 , 0.39973186, 0.23658785, 0.80286108, 0.1279529 ]])

In [46]:
#Ex 1. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
#
#
#

In [47]:
A = rng.randint(0,6 , (4,4))
A

array([[3, 2, 2, 5],
       [2, 2, 0, 5],
       [0, 5, 2, 3],
       [1, 5, 5, 2]])

In [48]:
A = np.delete(A, 1, axis = 0)
A 

array([[3, 2, 2, 5],
       [0, 5, 2, 3],
       [1, 5, 5, 2]])

In [49]:
A = np.delete(A, 1, axis = 1)
A

array([[3, 2, 5],
       [0, 2, 3],
       [1, 5, 2]])

In [50]:
np_matrix = rng.randint(0,2, (4,4))
np_matrix

array([[0, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 1]])

In [51]:
rows, cols = np.where(np_matrix == 0)
[ [row, cols[i]] for i, row in enumerate(rows) ]

[[0, 0], [0, 2], [1, 0], [1, 1], [1, 2], [1, 3], [2, 1], [3, 1]]

In [52]:
#Ex 2. Why we cannot use this index ? Please fix it !!
#idx = [1,2,3,4,5]
#np_matrix[idx,:]

In [53]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[4, 0, 5, 3, 9],
       [5, 4, 4, 9, 1],
       [8, 2, 0, 4, 3],
       [1, 8, 9, 6, 3],
       [2, 9, 0, 9, 2]])

In [54]:
result = (np_matrix == 2)
result

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False,  True]])

In [55]:
np_matrix[result] = 99
np_matrix

array([[ 4,  0,  5,  3,  9],
       [ 5,  4,  4,  9,  1],
       [ 8, 99,  0,  4,  3],
       [ 1,  8,  9,  6,  3],
       [99,  9,  0,  9, 99]])

In [56]:
# Ex 3. 
# 1. Randomly create a data matrix of 10 samples with 5 features. 
# 2. Then, randomly create a label vector for 10 samples as (0 and 1) # [0,1,0,0,1,1,1,0,0,0]
# 3. Finally, seperate data matrix into 2 groups
# 4. Group 1 data with label == 0
# 5. Group 2 data with label == 1

In [57]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[2, 4, 2, 4, 3],
       [1, 2, 5, 2, 2],
       [5, 5, 2, 4, 1],
       [3, 3, 2, 2, 1],
       [2, 3, 4, 5, 2]])

In [58]:
np.max(data)

5

In [59]:
np.max(data,0)

array([5, 5, 5, 5, 3])

In [60]:
np.max(data,1)

array([4, 5, 5, 3, 5])

In [61]:
np.sum(data)

71

In [62]:
np.sum(data, axis=0)

array([13, 17, 15, 17,  9])

In [63]:
np.sum(data, axis=1)

array([15, 12, 17, 11, 16])

In [64]:
np.average(data)

2.84

In [65]:
data[0,:]

array([2, 4, 2, 4, 3])

In [66]:
np.argmax(data[0,:])

1

In [67]:
np.argmin(data[0,:])

0

In [68]:
np.sort(data[0,:])

array([2, 2, 3, 4, 4])

In [69]:
np.argsort(data[0,:])

array([0, 2, 4, 1, 3])

In [70]:
#Ex.4 How to sort in decreasing order using np.sort
#

In [71]:
np.arange(1,10,3)

array([1, 4, 7])

In [72]:
np.linspace(0,4,20)

array([0.        , 0.21052632, 0.42105263, 0.63157895, 0.84210526,
       1.05263158, 1.26315789, 1.47368421, 1.68421053, 1.89473684,
       2.10526316, 2.31578947, 2.52631579, 2.73684211, 2.94736842,
       3.15789474, 3.36842105, 3.57894737, 3.78947368, 4.        ])

In [73]:
data = np.round(rng.random((5,5))*3)
data

array([[3., 1., 3., 2., 1.],
       [3., 1., 1., 2., 3.],
       [2., 1., 3., 3., 0.],
       [1., 2., 1., 2., 2.],
       [0., 2., 2., 3., 2.]])

In [74]:
data.shape

(5, 5)

In [75]:
data.reshape(1,25)

array([[3., 1., 3., 2., 1., 3., 1., 1., 2., 3., 2., 1., 3., 3., 0., 1.,
        2., 1., 2., 2., 0., 2., 2., 3., 2.]])

In [76]:
a = [[1,2],
     [3,4]]
a

[[1, 2], [3, 4]]

In [77]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [78]:
c = np.vstack((a,b))
c

array([[1., 2.],
       [3., 4.],
       [0., 0.],
       [0., 0.]])

In [79]:
c = np.hstack((a,b))
c

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.]])

In [80]:
# Ex.5 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
#
np_test = np.reshape(np.arange(0,25), (5,5))
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

<h1> Association Rules for Business Data Analytics </h1>

In [81]:
products = np.array(['ขนมปัง', 'ไข่', 'เนย', 'น้ำเปล่า', 'ข้าว'])

In [82]:
basket = [ [1,1,1,0,0],
           [1,0,1,1,0],
           [1,0,0,1,1],
           [0,1,0,1,0] ]
basket = np.array(basket)

In [83]:
products[basket[0]==1]

array(['ขนมปัง', 'ไข่', 'เนย'], dtype='<U8')

In [84]:
number_of_basket = len(basket)

In [85]:
number_of_product = np.sum(basket, axis=0)
item_support1 = [[products[i], item/number_of_basket ]  for i,item in enumerate(number_of_product) ]
item_support1

[['ขนมปัง', 0.75],
 ['ไข่', 0.5],
 ['เนย', 0.5],
 ['น้ำเปล่า', 0.75],
 ['ข้าว', 0.25]]

In [86]:
item_support2 = [[pair_product[i], item/number_of_basket ]  for i,item in enumerate(number_of_product2) ]
item_support2

NameError: name 'number_of_product2' is not defined

In [ ]:
pair_product = [ [products[i], products[j]]  for i in range(0,len(products)) for j in range(i+1, len(products))]
pair_product

In [ ]:
number_of_product2 = []
for one, two in pair_product:
    number_of_product2.append(np.sum([1 for eachbasket in basket if eachbasket[products==one] == 1 and eachbasket[products==two] == 1]))
number_of_product2

<h2> Confidence </h2>

Confidence(LHS => RHS) = Support(LHS, RHS)/Support(LHS)

In [ ]:
#ขนมปัง => เนย
0.5/0.75

In [ ]:
#เนย => ขนมปัง
0.5/0.5

<h2> Lift </h2>

Lift(LHS=>RHS) = Confidence(LHS=>RHS) / Support(RHS)

In [ ]:
#ขนมปัง => เนย
0.6666666667/0.5

In [ ]:
0.5/(0.75*0.5)

In [ ]:
#เนย => ขนมปัง
1/0.75

In [ ]:
0.5/(0.5*0.75)

In [ ]:
#Ex 1. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
#
#
#

In [ ]:
a = np.random.randint(10,size = (10,5))
a[::,-1] = np.random.randint(0,2,10)
a

In [ ]:
#test การสุ่มค่า 0,1 แถวล่างสุด
a = np.random.randint(10,size = (10,5))
a[-1::] = np.random.randint(0,2,5)
a

In [ ]:
#Ex 2. Why we cannot use this index ? Please fix it !!
#idx = [1,2,3,4,5]
#np_matrix[idx,:]

In [ ]:
np_matrix = rng.randint(0,2, (6,6))
idx = [0,1,2,3,4,5]
np_matrix[idx,:]

In [ ]:
np_matrix = rng.randint(0,2, (6,6))
np_matrix

In [ ]:
idx = [0,1,2,3,4,5]
np_matrix[idx,:]

In [ ]:
# Ex 3. 
# 1. Randomly create a data matrix of 10 samples with 5 features. 
# 2. Then, randomly create a label vector for 10 samples as (0 and 1) # [0,1,0,0,1,1,1,0,0,0]
# 3. Finally, seperate data matrix into 2 groups
# 4. Group 1 data with label == 0
# 5. Group 2 data with label == 1

In [ ]:
#label_vector
np.random.randint(0,2,10)

In [ ]:
#label_vector
a = np.random.randint(100,size = (10,5))
a[::, -1] = np.random.randint(0,2,10)
a

In [ ]:
# Ex 3. 
# 1. Randomly create a data matrix of 10 samples with 5 features. 
# 2. Then, randomly create a label vector for 10 samples as (0 and 1) # [0,1,0,0,1,1,1,0,0,0]
# 3. Finally, seperate data matrix into 2 groups
# 4. Group 1 data with label == 0
# 5. Group 2 data with label == 1

In [ ]:
#data_matrix
np_matrix = np.random.randint(100,size = (10,5))
np_matrix

In [ ]:
#label_vector
label = np.random.randint(0,2,10)
label

In [ ]:
A1 = np_matrix[label==0, :]
A2 = np_matrix[label==1, :]

In [ ]:
A1

In [ ]:
A2

In [ ]:
Group1 = [];
Group2 = [];

for i in range(10):
    if label[i] == 0:
        Group1.append(list(np_matrix[i]))
    else:
        Group2.append(list(np_matrix[i]))

In [ ]:
#group 1 == 0
list(Group1)

In [ ]:
#group 2 == 1
list(Group2)

In [ ]:
#Ex.4 How to sort in decreasing order using np.sort
#

In [ ]:
a = np.array([5,2,7,4,4,2,8,6,4,4])
-np.sort(-a)

In [ ]:
a[::-1].sort()
a

In [ ]:
# Ex.5 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
#
np_test = np.reshape(np.arange(0,25), (5,5))
np_test

In [ ]:
# Ex.5 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
#np_test = np.reshape(np.arange(0,35), (10,5))
#np_test

In [ ]:
np.fill_diagonal(np_test,[0])
np_test

In [ ]:
breakfast = np.array(['ขนมปัง','แฮม','ไข่','เครื่องดื่ม','ผลไม้'])

In [ ]:
customer = [ [1,1,1,0,1],
             [0,1,1,0,0],
             [1,0,0,1,1],
             [1,0,1,0,0] ]
customer = np.array(customer)

In [ ]:
breakfast[customer[0]==1]

In [ ]:
number_of_customer = len(customer)

In [ ]:
number_of_breakfast = np.sum(customer, axis=0)
item_support1 = [[breakfast[i], item/number_of_customer ]  for i,item in enumerate(number_of_breakfast) ]
item_support1

In [ ]:
pair_breakfast = [ [breakfast[i], breakfast[j]]  for i in range(0,len(breakfast)) for j in range(i+1, len(breakfast))]
pair_breakfast

In [ ]:
number_of_breakfast2 = []
for one, two in pair_breakfast:
    number_of_breakfast2.append(np.sum([1 for eachcustomer in customer if eachcustomer[breakfast==one] == 1 and eachcustomer[breakfast==two] == 1]))
number_of_breakfast2

In [ ]:
item_support2 = [[pair_breakfast[i], item/number_of_customer]  for i,item in enumerate(number_of_breakfast2) ]
item_support2

<h2> Confidence </h2>

In [ ]:
#แฮม => ไข่
0.5/0.5

In [ ]:
#ขนมปัง => ไข่
0.5/0.75

<h2> Lift </h2>

ความน่าจะเป็นที่ลูกค้าจะหยิบไข่ หลังจากที่ลูกค้าหยิบแฮมลงตะกร้าไปแล้ว เพิ่มหรือลดเป็นจำนวนกี่เท่าของความน่าจะเป็นที่ลูกค้าจะซื้อไข่โดยปกติ

ค่ามากกว่า 1 เพิ่มความน่าจะเป็นในการหยิบเพิ่มสูง

In [ ]:
#แฮม => ไข่
1/0.75

In [ ]:
0.5/(0.5*0.75)

In [ ]:
#ขนมปัง => ไข่
0.6666666666666666/0.75

In [ ]:
0.5/(0.75*0.75)